### PR TITLE
unicode deserialization support for 1.9.2

### PR DESCRIPTION
**Pull request by dapi**
Hello!

What do you think about indentation by 2 spaces? :)

### CODE REVIEW

**Comment by uhees** [comment]
I agree. I have fixed the indentation of the method comments and converted the tabs to spaces.

What I don't currently agree on is the unicode changes. I use the gem for reading real PHP session data. PHP does not care about encodings, so you have to know on the ruby side which encoding is used on the php side.

I have added your cyrillic test (with modified byte count) and it runs fine.

**Comment by dapi** [comment]
Hmm.. Yes, it's runs fine on your repo. Looking for real breaking serialization

**Comment by uhees** [comment]
If you are processing PHP serialization data that is stored in CP-1251 or KOI8-R you could try opening the serialization file with open("serialization_data", "r:KOI8-R:UTF-8") which means read in KOI8-R and internally represent as UTF-8.

This might help http://blog.grayproductions.net/articles/ruby_19s_three_default_encodings

**Comment by dapi** [comment]
No it's not CP or KOI, it is utf-8. But I catched encoding error again:

```
ruby ./test.rb
Loaded suite ./test
Started
....................F
Finished in 0.007480 seconds.

  1) Failure:
test_ümläut_test(TestPhpSerialize) [./test.rb:42]:
<"s:13:\"ümläut_test\";"> expected but was
<"s:11:\"ümläut_test\";">.

21 tests, 59 assertions, 1 failures, 0 errors, 0 skips

Test run options: --seed 22173

> ruby --version
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin10.8.0]
```

Can't understand - why it pass or not pass sometimes..

**Pull request merged**
